### ISSUE TITLE
Inadequate unit test "TestSplitRealAndImaginary"

### ISSUE THREAD

**Issue by avcarr2** [avcarr2/FCWTNET#20]
The unit test for TestSplitRealAndImaginary doesn't test that the splitting is working. It uses the already split array to check that the array splitting is working.

**Comment by zdanaceau** [comment]
What do you mean by this? In my unit test for that function I check the real and imaginary components against the original CWT array which should not be split.
![image](https://user-images.githubusercontent.com/100874533/181117563-26aa93b5-8d47-4018-8576-4efbacb8e6c7.png)

**Comment by avcarr2** [comment]
Upon further review, I think we can just go ahead and remove this method and unit test.
