### ISSUE TITLE
Deprecated methods? 

### ISSUE THREAD

**Issue by avcarr2** [avcarr2/FCWTNET#22]
* https://github.com/avcarr2/FCWTNET/blob/f4dfb6842f356466f743610df35d327a6a1eee01/FCWTAPI/CWTObject.cs#L64
* https://github.com/avcarr2/FCWTNET/blob/f4dfb6842f356466f743610df35d327a6a1eee01/FCWTAPI/CWTObject.cs#L89
* https://github.com/avcarr2/FCWTNET/blob/f4dfb6842f356466f743610df35d327a6a1eee01/FCWTAPI/CWTObject.cs#L115

**Comment by zdanaceau** [comment]
This has been resolved in our recent refactoring.
